import JSZip from 'jszip';

export const downloadProjectAsZip = async (projectData, projectName = 'ai-generated-website') => {
  try {
    const zip = new JSZip();
    
    // Add HTML file
    if (projectData.html) {
      zip.file('index.html', projectData.html);
    }
    
    // Add CSS file if provided separately
    if (projectData.css) {
      zip.file('styles.css', projectData.css);
    }
    
    // Add JavaScript file if provided separately
    if (projectData.js) {
      zip.file('script.js', projectData.js);
    }
    
    // Add README with project info
    const readme = `# ${projectName}

## AI Generated Website

**Description:** ${projectData.description || 'AI generated website'}

**Generated on:** ${new Date().toLocaleDateString()}

## Files Included:
- index.html - Main HTML file
${projectData.css ? '- styles.css - CSS stylesheet' : ''}
${projectData.js ? '- script.js - JavaScript functionality' : ''}

## How to Use:
1. Extract this ZIP file
2. Open index.html in your web browser
3. Customize the code as needed

---
Generated by AI UI Builder
`;
    
    zip.file('README.md', readme);
    
    // Generate and download the ZIP file
    const content = await zip.generateAsync({ type: 'blob' });
    
    // Create download link
    const url = window.URL.createObjectURL(content);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${projectName.replace(/[^a-z0-9]/gi, '-').toLowerCase()}.zip`;
    
    // Trigger download
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    
    // Clean up
    window.URL.revokeObjectURL(url);
    
    return { success: true };
  } catch (error) {
    console.error('Error creating ZIP file:', error);
    return { 
      success: false, 
      error: 'Failed to create ZIP file' 
    };
  }
};
